enum ActionTypes {
  AUTHENTICATE = 'authentication/AUTHENTICATE',
  AUTHENTICATE_SUCCESS = 'authentication/AUTHENTICATE_SUCCESS',
  AUTHENTICATE_ERROR = 'authentication/AUTHENTICATE_ERROR',

  RESET_AUTHENTICATION = 'authentication/RESET_AUTHENTICATION',

  CHECK_BIOMETRIC_SUPPORTED = 'authentication/CHECK_BIOMETRIC_SUPPORTED',
  CHECK_BIOMETRIC_SUPPORTED_SUCCESS = 'authentication/CHECK_BIOMETRIC_SUPPORTED_SUCCESS',
  CHECK_BIOMETRIC_SUPPORTED_ERROR = 'authentication/CHECK_BIOMETRIC_SUPPORTED_ERROR',

  GET_BIOMETRIC_TYPES = 'authentication/GET_BIOMETRIC_TYPES',
  GET_BIOMETRIC_TYPES_SUCCESS = 'authentication/GET_BIOMETRIC_TYPES_SUCCESS',
  GET_BIOMETRIC_TYPES_ERROR = 'authentication/GET_BIOMETRIC_TYPES_ERROR',

  CHECK_SAVED_BIOMETRICS = 'authentication/CHECK_SAVED_BIOMETRICS',
  CHECK_SAVED_BIOMETRICS_SUCCESS = 'authentication/CHECK_SAVED_BIOMETRICS_SUCCESS',
  CHECK_SAVED_BIOMETRICS_ERROR = 'authentication/CHECK_SAVED_BIOMETRICS_ERROR',
}

export default ActionTypes;
