enum ActionTypes {
  CREATE_TODO = 'todo/CREATE_TODO',
  CREATE_TODO_SUCCESS = 'todo/CREATE_TODO_SUCCESS',
  CREATE_TODO_ERROR = 'todo/CREATE_TODO_ERROR',

  UPDATE_TODO = 'todo/UPDATE_TODO',
  UPDATE_TODO_SUCCESS = 'todo/UPDATE_TODO_SUCCESS',
  UPDATE_TODO_ERROR = 'todo/UPDATE_TODO_ERROR',

  DELETE_TODOS = 'todo/DELETE_TODOS',
  DELETE_TODOS_SUCCESS = 'todo/DELETE_TODOS_SUCCESS',
  DELETE_TODOS_ERROR = 'todo/DELETE_TODOS_ERROR',

  CHANGE_TODO_CONTENT = 'todo/CHANGE_TODO_CONTENT',
  SET_TODO_MODE = 'todo/SET_TODO_MODE',

  TICK_TODO = 'todo/TICK_TODO',
}

export default ActionTypes;
